// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using appointment_service.Persistence;

#nullable disable

namespace appointment_service.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251202081445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("appointment_service")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("appointment_service.Persistence.Entities.AppointmentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_number");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time");

                    b.HasKey("Id")
                        .HasName("pk_appointment_request");

                    b.ToTable("appointment_request", "appointment_service");
                });

            modelBuilder.Entity("appointment_service.Persistence.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("BranchCode")
                        .HasColumnType("integer")
                        .HasColumnName("branch_code");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("branch_name");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_number");

                    b.Property<string>("Provice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provice");

                    b.Property<int>("SlotPerHour")
                        .HasColumnType("integer")
                        .HasColumnName("slot_per_hour");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("suburb");

                    b.HasKey("Id")
                        .HasName("pk_branch");

                    b.ToTable("branch", "appointment_service");
                });

            modelBuilder.Entity("appointment_service.Persistence.Entities.OperationalHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("interval")
                        .HasColumnName("close_time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("interval")
                        .HasColumnName("open_time");

                    b.HasKey("Id")
                        .HasName("pk_operational_hours");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_operational_hours_branch_id");

                    b.ToTable("operational_hours", "appointment_service");
                });

            modelBuilder.Entity("appointment_service.Persistence.Entities.AppointmentRequest", b =>
                {
                    b.OwnsOne("appointment_service.Persistence.Entities.CustomerInfo", "Customer", b1 =>
                        {
                            b1.Property<Guid>("AppointmentRequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("appointment_request_id");

                            b1.Property<string>("ContactNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("contact_number");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("full_name");

                            b1.Property<string>("IdNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("id_number");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("notes");

                            b1.HasKey("AppointmentRequestId")
                                .HasName("pk_customer_info");

                            b1.ToTable("customer_info", "appointment_service");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentRequestId")
                                .HasConstraintName("fk_customer_info_appointment_request_appointment_request_id");
                        });

                    b.Navigation("Customer")
                        .IsRequired();
                });

            modelBuilder.Entity("appointment_service.Persistence.Entities.OperationalHours", b =>
                {
                    b.HasOne("appointment_service.Persistence.Entities.Branch", "Branch")
                        .WithMany("OperationalHours")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operational_hours_branch_branch_id");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("appointment_service.Persistence.Entities.Branch", b =>
                {
                    b.Navigation("OperationalHours");
                });
#pragma warning restore 612, 618
        }
    }
}
